In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats as stats
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv(
    r'C:\Users\25492\Desktop\2024年第四届长三角高校数学建模竞赛赛题\2024长三角选题B：人工智能范式的物理化学家\data.csv')
data

id  class          y1        y2        y3        x1        x2  \
0            1      2 -587.360784 -0.331308  0.018453  0.136518  0.000059   
1            2      2 -587.359946 -0.329316  0.020334  0.135966  0.000060   
2            3      2 -587.366330 -0.324781  0.024104  0.136758  0.000058   
3            4      1 -534.430563 -0.323772  0.076703  0.166028  0.000058   
4            5      2 -838.152165 -0.323753 -0.038820  0.169158  0.000067   
...        ...    ...         ...       ...       ...       ...       ...   
199995  199996      1 -419.504748 -0.152722 -0.025667  0.169241  0.000055   
199996  199997      1 -419.494291 -0.152693 -0.018547  0.168173  0.000059   
199997  199998      2 -406.836695 -0.152680 -0.041361  0.233604  0.000067   
199998  199999      1 -440.592967 -0.152678 -0.008569  0.180136  0.000060   
199999  200000      3 -463.293589 -0.152657 -0.021764  0.270812  0.000083   

              x3          x4          x5  ...         x91        x92  \
0       0.349761 -587.313385   68.127640  ...  121.932271  39.136162   
1       0.349651 -587.313067   68.406902  ...  193.540254  33.530111   
2       0.348885 -587.319604   67.688007  ...  187.885229  15.181060   
3       0.400475 -534.384191   66.933953  ...   53.692333  48.561113   
4       0.284934 -838.102038   90.368137  ...    7.836116  48.199369   
...          ...         ...         ...  ...         ...        ...   
199995  0.127055 -419.459364   79.538702  ...   63.361697  39.151228   
199996  0.134146 -419.448829   78.753240  ...  110.211710   0.088873   
199997  0.111320 -406.786417  108.276082  ...   13.798549  37.889274   
199998  0.144109 -440.548209   76.762032  ...   29.168705  15.882359   
199999  0.130893 -463.239421  112.452495  ...  165.696065  42.040440   

               x93          x94          x95           x96          x97  \
0       167.944447   810.320131  1310.347942  28259.325400  2204.278945   
1       820.070309   332.223854  1224.970065  19185.769380  2076.587979   
2       149.626389  1935.124281  3766.649406  10780.248220   497.946181   
3       240.029692  2747.138536  2553.341043   7180.522100  2518.506658   
4       490.018016  1496.939717  1507.517227  24619.776720  2971.889099   
...            ...          ...          ...           ...          ...   
199995   94.862755  1968.900543   501.442536  14489.037340  1554.543619   
199996  139.355293  1608.385691  1017.910470  19022.048140  2359.630960   
199997  828.723926  2080.905500   776.676895  11712.821270  2686.690842   
199998  654.330446   620.222337  2396.827918   6858.319928  1065.978203   
199999  212.433831  2321.119201   736.981524  14759.075440  1735.312436   

                 x98           x99        x100  
0       21606.405010  16746.254820  213.098000  
1       17602.163970   2199.601888  506.651409  
2       16759.458980  17687.268850  575.511247  
3       37359.799660   5784.140268  530.878047  
4       36697.285060  17496.357370  640.112190  
...              ...           ...         ...  
199995  26717.867000   6227.496125  548.720052  
199996  22182.780890  19762.010290  194.794578  
199997   3036.807908   2058.707100  474.257489  
199998   9818.305268   6949.049915  502.028596  
199999   9564.510604  18369.448760  580.469209  

[200000 rows x 105 columns]

# 1. 变量选择

In [126]:
X = data.iloc[:,5:] # x1-x100
Y = data.iloc[:,4]# class
Y

0         0.018453
1         0.020334
2         0.024104
3         0.076703
4        -0.038820
            ...   
199995   -0.025667
199996   -0.018547
199997   -0.041361
199998   -0.008569
199999   -0.021764
Name: y3, Length: 200000, dtype: float64

In [127]:
# 套索回归选择变量
from sklearn.linear_model import LassoCV
# 数据预处理：标准化特征
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
 
# 使用LassoCV自带正则化路径长度和路径中的alpha个数来自动建立alpha选择的范围
ls_ = LassoCV(eps=0.0001,n_alphas=300,cv=5).fit(X_scaled,Y)
# 可以查看哪些特征的系数被压缩到零，实现了特征选择
non_zero_coef_indices = np.abs(ls_.coef_) != 0
selected_features = np.arange(X.shape[1])[non_zero_coef_indices]
print("Selected Features (indices): ", selected_features)
 
# 输出系数
coef = ls_.coef_
print("Lasso Coefficients: ", coef)

Selected Features (indices):  [0 2 3 5 7]
Lasso Coefficients:  [ 7.77619392e-03 -0.00000000e+00  3.51687672e-02  2.25776585e-04
  0.00000000e+00  6.87033267e-08  0.00000000e+00 -3.87564879e-03
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.0000000

In [128]:
X_selected = X.iloc[:,selected_features]
X_selected

x1        x3          x4          x6        x8
0       0.136518  0.349761 -587.313385 -587.323859  3.690374
1       0.135966  0.349651 -587.313067 -587.323542  3.720941
2       0.136758  0.348885 -587.319604 -587.329854  3.111271
3       0.166028  0.400475 -534.384191 -534.394372  2.187990
4       0.169158  0.284934 -838.102038 -838.113854  4.485350
...          ...       ...         ...         ...       ...
199995  0.169241  0.127055 -419.459364 -419.468874  3.991411
199996  0.168173  0.134146 -419.448829 -419.458752  5.784022
199997  0.233604  0.111320 -406.786417 -406.797683  1.670824
199998  0.180136  0.144109 -440.548209 -440.558158  4.513365
199999  0.270812  0.130893 -463.239421 -463.253360  3.920614

[200000 rows x 5 columns]

In [129]:
# 分析选择的变量之间的独立性
S_x = np.zeros([X_selected.shape[1],X_selected.shape[1]])
for i in range(X_selected.shape[1]):
    for j in range(X_selected.shape[1]):
        S_x[i,j] = stats.spearmanr(X_selected.iloc[:,i],X_selected.iloc[:,j])[0]
S_x = pd.DataFrame(S_x,index=X_selected.columns, columns=X_selected.columns)
#S_x.to_csv('X变量之间相关系数矩阵_class.csv')
S_x

x1        x3        x4        x6        x8
x1  1.000000  0.419549  0.218928  0.218936 -0.442242
x3  0.419549  1.000000  0.126018  0.126057 -0.159737
x4  0.218928  0.126018  1.000000  1.000000 -0.285553
x6  0.218936  0.126057  1.000000  1.000000 -0.285570
x8 -0.442242 -0.159737 -0.285553 -0.285570  1.000000

In [130]:
X_selected = X_selected.drop(['x4'], axis=1)
X_selected

x1        x3          x6        x8
0       0.136518  0.349761 -587.323859  3.690374
1       0.135966  0.349651 -587.323542  3.720941
2       0.136758  0.348885 -587.329854  3.111271
3       0.166028  0.400475 -534.394372  2.187990
4       0.169158  0.284934 -838.113854  4.485350
...          ...       ...         ...       ...
199995  0.169241  0.127055 -419.468874  3.991411
199996  0.168173  0.134146 -419.458752  5.784022
199997  0.233604  0.111320 -406.797683  1.670824
199998  0.180136  0.144109 -440.558158  4.513365
199999  0.270812  0.130893 -463.253360  3.920614

[200000 rows x 4 columns]

# 2.集成学习器对比

In [70]:
from sklearn.model_selection import cross_val_score as cv 

## 2.1 分类

In [71]:
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.ensemble import ExtraTreesClassifier as ETC
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.ensemble import AdaBoostClassifier as ABC
from sklearn.ensemble import HistGradientBoostingClassifier as HGBC

In [72]:
rfc = RFC(n_estimators=100, max_depth=200, random_state=0)
etc = ETC(n_estimators=100, max_depth=200, random_state=0)
abc = ABC(DTC(max_depth=200), n_estimators=100, random_state=420)
hgbc = HGBC(max_iter=500, max_depth=200, random_state=420)

In [75]:
print('RFC_score_mean:',cv(rfc,X_selected,Y,cv=5).mean())
print('ETC_score_mean:',cv(etc,X_selected,Y,cv=5).mean())
print('ABC_score_mean:',cv(abc,X_selected,Y,cv=5).mean())
print('HGBC_score_mean:',cv(hgbc,X_selected,Y,cv=5).mean())

RFC_score_mean: 0.99082
ETC_score_mean: 0.98844
ABC_score_mean: 0.9869749999999999
HGBC_score_mean: 0.987935


## 2.2 回归

In [24]:
from sklearn.ensemble import GradientBoostingRegressor as GBR
from sklearn.ensemble import HistGradientBoostingRegressor as HGBR
from sklearn.ensemble import RandomForestRegressor as RFR
from sklearn.linear_model import LinearRegression as LR
from sklearn.ensemble import VotingRegressor as VG
from sklearn.ensemble import AdaBoostRegressor as ABR
from sklearn.tree import DecisionTreeRegressor as DTR

In [25]:
gbr = GBR(n_estimators=100, max_depth=200, random_state=0)
rfr = RFR(n_estimators=100, max_depth=200, random_state=0)
abr = ABR(DTR(max_depth=200, random_state=0), n_estimators=100)

In [28]:
print('ABR_score_mean:',cv(abr,X_selected,Y,cv=5).mean())
print('GBR_score_mean:',cv(gbr,X_selected,Y,cv=5).mean())
print('RFR_score_mean:',cv(rfr,X_selected,Y,cv=5).mean())

ABR_score_mean: 0.7194902325934633
GBR_score_mean: 0.6607819746210071
RFR_score_mean: 0.7120755403431696


In [32]:
print('ABR_score_mean:',cv(abr,X_selected,Y,cv=5).mean())

ABR_score_mean: 0.724371085346265


In [85]:
hgbr = HGBR( max_iter=1000, max_depth=200, random_state=0)
print('hgbr_score_mean:',cv(hgbr,X_selected,Y,cv=5).mean())

hgbr_score_mean: 0.9939820152532013


# 3.y1预测

In [41]:
from sklearn.model_selection import train_test_split as TTS
#数据切分
Xtrain, Xtest, Ytrain, Ytest = TTS(X_selected,Y,test_size=0.3,random_state=420)

In [42]:
abr = ABR(DTR(max_depth=200, random_state=0), n_estimators=100)
abr.fit(Xtrain,Ytrain)

AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=200,
                                                  random_state=0),
                  n_estimators=100)

In [43]:
# 测试
Ytest_pre = abr.predict(Xtest)
Ytest_pre

array([-423.9577618, -404.6216799, -443.1437956, ..., -497.2860761,
       -386.6109506, -426.1358675])

In [45]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
# 测试评估
MAE = mean_absolute_error(Ytest,Ytest_pre)
MSE = mean_squared_error(Ytest,Ytest_pre)
MAPE = mean_absolute_percentage_error(Ytest,Ytest_pre)
print('MAE:',MAE)
print('MSE:',MSE)
print('MAPE:',MAPE)

MAE: 0.0032659516036150716
MSE: 0.015187637857564006
MAPE: 5.465641383277026e-06


# 4.y3预测

In [60]:
from sklearn.model_selection import train_test_split as TTS
#数据切分
Xtrain, Xtest, Ytrain, Ytest = TTS(X_selected,Y,test_size=0.3,random_state=420)

In [61]:
hgbr = HGBR( max_iter=1000, max_depth=200, random_state=0)
hgbr.fit(Xtrain,Ytrain)

HistGradientBoostingRegressor(max_depth=200, max_iter=1000, random_state=0)

In [62]:
# 测试
Ytest_pre = hgbr.predict(Xtest)
Ytest_pre

array([ 0.07909823, -0.04519803,  0.01570214, ..., -0.02236965,
       -0.02714296,  0.02631823])

In [63]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
# 测试评估
MAE = mean_absolute_error(Ytest,Ytest_pre)
MSE = mean_squared_error(Ytest,Ytest_pre)
MAPE = mean_absolute_percentage_error(Ytest,Ytest_pre)
print('MAE:',MAE)
print('MSE:',MSE)
print('MAPE:',MAPE)

MAE: 0.008696688330478321
MSE: 0.00014921813371025086
MAPE: 1.3135455207061904


# 5.class预测

In [76]:
from sklearn.model_selection import train_test_split as TTS
#数据切分
Xtrain, Xtest, Ytrain, Ytest = TTS(X_selected,Y,test_size=0.3,random_state=420)

In [77]:
rfc = RFC(n_estimators=100, max_depth=200, random_state=0)
rfc.fit(Xtrain,Ytrain)

RandomForestClassifier(max_depth=200, random_state=0)

In [78]:
# 测试
Ytest_pre = rfc.predict(Xtest)
Ytest_pre

array([1, 1, 3, ..., 4, 2, 2], dtype=int64)

In [87]:
# 测试评估
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
report = classification_report(Ytest, Ytest_pre)
print(report)
accuracy_rate = sum(Ytest==Ytest_pre)/len(Ytest)
print('accuracy_rate:', accuracy_rate)
c = confusion_matrix(Ytest, Ytest_pre)
print(c)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00     10396
           2       1.00      1.00      1.00     35562
           3       0.99      0.99      0.99     11259
           4       0.99      0.98      0.99      2783

    accuracy                           1.00     60000
   macro avg       1.00      0.99      0.99     60000
weighted avg       1.00      1.00      1.00     60000

accuracy_rate: 0.9962666666666666
[[10351    45     0     0]
 [   11 35497    54     0]
 [    0    49 11194    16]
 [    0     0    49  2734]]


# 6.输出预测

In [88]:
# 预测集
data_pre = pd.read_csv(r'C:\Users\25492\Desktop\2024年第四届长三角高校数学建模竞赛赛题\2024长三角选题B：人工智能范式的物理化学家\predict.csv')
data_pre

id  class  y1  y2  y3        x1        x2        x3          x4  \
0     200001    NaN NaN NaN NaN  0.226002  0.000065  0.132347 -368.670646   
1     200002    NaN NaN NaN NaN  0.214187  0.000066  0.130316 -384.732758   
2     200003    NaN NaN NaN NaN  0.197361  0.000073  0.127443 -367.439885   
3     200004    NaN NaN NaN NaN  0.215407  0.000062  0.135675 -384.716532   
4     200005    NaN NaN NaN NaN  0.214432  0.000067  0.131066 -384.734795   
...      ...    ...  ..  ..  ..       ...       ...       ...         ...   
2575  202576    NaN NaN NaN NaN  0.158960  0.000058  0.084260 -398.477759   
2576  202577    NaN NaN NaN NaN  0.158984  0.000058  0.087399 -398.473992   
2577  202578    NaN NaN NaN NaN  0.158988  0.000058  0.087139 -398.474052   
2578  202579    NaN NaN NaN NaN  0.215280  0.000075  0.084348 -476.991234   
2579  202580    NaN NaN NaN NaN  0.238438  0.000074  0.136008 -519.068821   

              x5  ...         x91        x92         x93          x94  \
0      96.074011  ...   11.071498   5.344349  157.391719  1733.105035   
1      91.627267  ...    0.178717  24.201402   39.395577   966.750678   
2      93.450897  ...   76.092241  46.457823  443.755989    86.140490   
3      90.438786  ...  165.951655  50.797138  192.244542  1611.385190   
4      89.197619  ...  133.350895  65.631929  655.591805  2600.614565   
...          ...  ...         ...        ...         ...          ...   
2575   92.527055  ...  164.927555   2.287917  857.357218  2512.784553   
2576   89.497411  ...   37.542901  44.214331  637.825723  2453.167587   
2577   89.550594  ...    0.403145  35.282849  286.439254   812.043686   
2578  115.581030  ...   22.728919  58.773078  655.551793   681.650837   
2579  100.001487  ...   69.089652  31.298942  144.191410  3076.811482   

              x95           x96          x97           x98           x99  \
0     2139.033470   7279.073141  3484.772300  16080.595800    483.744199   
1     3040.168365  11974.531830  2475.110471  12965.566730  18545.231230   
2     1499.171629  17987.834790  3445.933673   7086.954277   2308.805257   
3     1041.286098  10741.318960  1557.125375  39992.132000   2207.866124   
4      584.201129  27283.461340  2535.635844  13134.988300  16068.260120   
...           ...           ...          ...           ...           ...   
2575   636.566533   9635.446798   380.996713    500.848858  23088.564540   
2576  3154.271089  10300.033380  1867.004962   2550.848129  22304.561400   
2577  2792.998726  17244.491480   103.067156  16822.422600  18641.183190   
2578  1184.057337  13679.670150  1285.024629  29956.280710  10683.200390   
2579   853.513743  22577.634890  2463.253742  10543.685740   9817.355422   

            x100  
0      89.146409  
1     689.034235  
2     337.999121  
3     506.676925  
4     477.398232  
...          ...  
2575  499.314824  
2576  344.708545  
2577  230.273167  
2578  351.671268  
2579  440.451156  

[2580 rows x 105 columns]

In [131]:
Xpre = data_pre.loc[:,X_selected.columns]
Xpre

x1        x3          x6        x8
0     0.226002  0.132347 -368.681892  0.819730
1     0.214187  0.130316 -384.744010  3.928610
2     0.197361  0.127443 -367.453626  0.908149
3     0.215407  0.135675 -384.727318  2.997407
4     0.214432  0.131066 -384.745961  4.176791
...        ...       ...         ...       ...
2575  0.158960  0.084260 -398.487127  1.801190
2576  0.158984  0.087399 -398.483464  1.394832
2577  0.158988  0.087139 -398.483517  1.823909
2578  0.215280  0.084348 -477.003702  1.901666
2579  0.238438  0.136008 -519.081196  2.326614

[2580 rows x 4 columns]

In [132]:
hgbr = HGBR( max_iter=1000, max_depth=200, random_state=0)
hgbr.fit(X_selected,Y)

HistGradientBoostingRegressor(max_depth=200, max_iter=1000, random_state=0)

In [133]:
Ypre = hgbr.predict(Xpre)
Ypre

array([-0.03958431, -0.02943224, -0.06409115, ..., -0.09557091,
       -0.10145665, -0.03724926])

In [134]:
# 创建空的DataFrame
df = pd.DataFrame(Ypre, columns=['y3'])
# 将DataFrame写入CSV文件
df.to_csv('y3_pre.csv', index=False)